modbus:
  host: 192.168.6.31
  port: 502
  timeout: 2.0
  retry_attempts: 3
  poll_interval_ms: 100
dyno:
  port_name: COM5
  rate: 9600
  bits: 8
  parity: N
  stopbit: 1
pid:
  kp: 0.5
  ki: 0.1
  kd: 0.0
ui:
  max_graph_points: 2000
  poll_interval_ms: 100
logging:
  level: INFO
  file: stand_control.log
graphs:
  tension plot:
    line_color: '#7eafff'
    background: '#FEFEFA'
    grid_color: '#C8C8C8'
    line_width: 2
  velocity plot:
    line_color: '#7eafff'
    background: '#FEFEFA'
    grid_color: '#C8C8C8'
    line_width: 2
stand:
  lab_address: чссчсмчм
  brand_and_model: цкцуке456
  serial_number: '546456456'
  certification_date: '3453453'
